name: vps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:       # cháº¡y thá»§ cÃ´ng
  schedule:
    - cron: "0 */5 * * *"  # cháº¡y láº¡i má»—i 6 tiáº¿ng (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: ğŸ”§ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: ğŸ“¦ CÃ i dependencies Node.js
        run: |
          npm install gradient-string@1.2.0
          npm install cheerio
          npm install axios
          npm install colors

      - name: ğŸš€ Run bot.py
        run: python3 bot.py
