name: vps

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # tá»± cháº¡y láº¡i má»—i 6 tiáº¿ng

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4
        
      - name: ğŸš€ Run VPS (sshx)
        run: |
          curl -sSf https://sshx.io/get | sh -s run &
          sleep 30
          echo "ğŸŸ¢ VPS SSHX Ä‘ang cháº¡y..."
